import type { RunFile } from "./cli.ts";
import type { Check, OptionResult } from "./verdict.ts";

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

const dash = "—";
const ms = (n?: number) => (n === undefined ? dash : n >= 1000 ? `${(n / 1000).toFixed(2)} s` : `${Math.round(n)} ms`);
const secs = (r: OptionResult) => {
  const f = r.freshness;
  if (!f) return dash;
  if (f.timed_out) return `over ${f.max_seconds} s`;
  return f.max_seconds < 1 ? "instant" : `${f.max_seconds} s`;
};
const lines = (r: OptionResult) => (r.diff ? `+${r.diff.added} −${r.diff.removed}` : dash);

interface Row {
  label: string;
  note?: string;
  value: (r: OptionResult) => string;
  check?: string;
}

function rows(data: RunFile): Row[] {
  const c = data.constraints;
  return [
    { label: "p95 latency", note: c.max_p95_ms !== undefined ? `needs ≤ ${c.max_p95_ms} ms` : undefined, value: (r) => ms(r.load?.p95_ms), check: "p95 latency" },
    { label: "Median latency", value: (r) => ms(r.load?.p50_ms) },
    { label: "Throughput", value: (r) => (r.load ? `${r.load.rps} req/s` : dash) },
    {
      label: "Staleness",
      note: c.max_staleness_seconds !== undefined ? `needs ≤ ${c.max_staleness_seconds} s` : "time until a new write shows up",
      value: secs,
      check: "Staleness",
    },
    { label: "Lines changed", value: lines },
    { label: "Files touched", value: (r) => (r.diff ? String(r.diff.files.length) : dash) },
    {
      label: "New dependencies",
      note: c.max_new_dependencies !== undefined ? `needs ≤ ${c.max_new_dependencies}` : undefined,
      value: (r) => (r.new_dependencies ? (r.new_dependencies.length ? r.new_dependencies.join(", ") : "none") : dash),
      check: "New dependencies",
    },
    {
      label: "Tests",
      value: (r) => (r.tests ? `${r.tests.ok ? "pass" : "fail"}${r.tests.passed !== null ? ` · ${r.tests.passed}` : ""}` : dash),
      check: "Tests",
    },
    { label: "Built by Bob in", value: (r) => (r.bob ? `${Math.floor(r.bob.duration_seconds / 60)}m ${r.bob.duration_seconds % 60}s` : dash) },
  ];
}

function mark(checks: Check[] | undefined, label?: string): string {
  if (!checks || !label) return "";
  const c = checks.find((x) => x.label === label);
  if (!c) return "";
  return c.pass ? `<span class="mk ok" title="meets constraint">✓</span>` : `<span class="mk no" title="misses constraint">✕</span>`;
}

export function renderAppendix(data: RunFile): string {
  const all = [data.baseline, ...data.options];
  const table = rows(data);
  const head = `| | ${all.map((r) => r.name).join(" | ")} |\n|---|${all.map(() => "---").join("|")}|`;
  const body = table.map((row) => `| ${row.label} | ${all.map((r) => row.value(r)).join(" | ")} |`).join("\n");
  const constraints = Object.entries(data.constraints)
    .map(([k, v]) => `\`${k}: ${v}\``)
    .join(", ");
  const branches = data.options.map((o) => `- ${o.name}: \`${o.branch}\`${o.build_error ? ` (not built: ${o.build_error})` : ""}`).join("\n");
  return `## Appendix: measured comparison

**Question:** ${data.question}

Each option was built by IBM Bob in its own branch from \`${data.base_commit.slice(0, 7)}\`, then measured with the same load test (${data.load.duration_seconds} s at concurrency ${data.load.concurrency}) and the same staleness probe.

${head}
${body}

**Constraints:** ${constraints || "none"}

**Verdict:** ${data.verdict.headline} ${data.verdict.reason}

**Branches:**
${branches}

_Generated by Settle on ${data.created_at.slice(0, 10)}._
`;
}

export function renderReport(data: RunFile): string {
  const all = [data.baseline, ...data.options];
  const table = rows(data);
  const winner = data.verdict.winner;
  const cls = (r: OptionResult) => (r.id === winner ? "win" : r.id === "baseline" ? "base" : "");
  const built = data.options.filter((o) => o.built).length;

  const thead = all
    .map((r) => `<th class="${cls(r)}" scope="col">${r.id === winner ? `<span class="tag">Pick</span>` : ""}<span class="oname">${esc(r.name)}</span></th>`)
    .join("");
  const tbody = table
    .map(
      (row) => `<tr>
  <th scope="row"><span class="rl">${esc(row.label)}</span>${row.note ? `<span class="rn">${esc(row.note)}</span>` : ""}</th>
  ${all
    .map((r) => {
      const v = r.built || r.id === "baseline" ? row.value(r) : r.id === "baseline" ? dash : "not built";
      return `<td class="${cls(r)}">${esc(v)}${r.id === "baseline" ? "" : mark(data.verdict.checks[r.id], row.check)}</td>`;
    })
    .join("")}
</tr>`,
    )
    .join("\n");

  const details = data.options
    .map(
      (o) => `<section class="opt">
  <h3>${esc(o.name)}${o.id === winner ? ` <span class="tag">Pick</span>` : ""}</h3>
  <p>${esc(o.description)}</p>
  ${o.build_error ? `<p class="err">Not built: ${esc(o.build_error)}</p>` : ""}
  ${o.measure_error ? `<p class="err">Measurement failed: ${esc(o.measure_error.split("\n")[0])}</p>` : ""}
  <p class="meta">Branch <code>${esc(o.branch)}</code></p>
  ${o.diff?.files.length ? `<ul class="files">${o.diff.files.map((f) => `<li><code>${esc(f)}</code></li>`).join("")}</ul>` : ""}
</section>`,
    )
    .join("\n");

  const appendix = renderAppendix(data);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Settle Results</title>
<meta name="description" content="${esc(data.question)}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
:root {
  --bg: #ffffff; --fg: #0b0b0c; --muted: #6b6b70; --line: #e4e4e7; --soft: #f5f5f6; --strong: #0b0b0c;
  --sans: "Inter Tight", ui-sans-serif, system-ui, sans-serif; --mono: "JetBrains Mono", ui-monospace, monospace;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { --bg: #0b0b0c; --fg: #f4f4f5; --muted: #9a9aa2; --line: #26262b; --soft: #141417; --strong: #f4f4f5; }
}
:root[data-theme="dark"] { --bg: #0b0b0c; --fg: #f4f4f5; --muted: #9a9aa2; --line: #26262b; --soft: #141417; --strong: #f4f4f5; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--fg); font: 16px/1.55 var(--sans); -webkit-font-smoothing: antialiased; }
.wrap { max-width: 1180px; margin: 0 auto; padding: 0 16px; }
header.bar { display: flex; justify-content: space-between; align-items: center; padding: 20px 0; border-bottom: 1px solid var(--line); font-size: 14px; }
.brand { font-weight: 800; letter-spacing: -0.02em; font-size: 18px; }
.muted { color: var(--muted); }
.hero { text-align: center; padding: 72px 0 40px; }
.eyebrow { font: 500 12px/1 var(--mono); letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); }
h1 { font-size: clamp(32px, 5.4vw, 64px); line-height: 1.04; letter-spacing: -0.035em; font-weight: 800; margin: 18px auto 18px; max-width: 16ch; }
.sub { color: var(--muted); max-width: 60ch; margin: 0 auto; }
.verdict { border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); padding: 36px 0; display: grid; grid-template-columns: 200px 1fr; gap: 24px; }
.verdict .k { font: 500 12px/1.4 var(--mono); letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); padding-top: 8px; }
.verdict p { margin: 0; color: var(--muted); max-width: 80ch; }
.verdict .h { font-size: clamp(22px, 3vw, 32px); font-weight: 700; letter-spacing: -0.02em; line-height: 1.15; margin: 0 0 10px; color: var(--fg); }
.tablewrap { overflow-x: auto; margin: 40px 0 8px; }
table { border-collapse: collapse; width: 100%; min-width: 720px; }
th, td { text-align: left; padding: 16px 14px; border-bottom: 1px solid var(--line); vertical-align: top; }
thead th { border-bottom: 2px solid var(--strong); font-weight: 600; font-size: 15px; padding-top: 0; }
thead th.win { border-bottom-width: 4px; }
tbody th { font-weight: 500; width: 210px; }
.rl { display: block; }
.rn { display: block; font: 400 12px/1.4 var(--mono); color: var(--muted); margin-top: 2px; }
td { font: 500 15px/1.4 var(--mono); white-space: nowrap; }
td.base { color: var(--muted); }
td.win { font-weight: 600; background: var(--soft); }
th.win { background: var(--soft); }
.mk { display: inline-block; margin-left: 8px; font-family: var(--sans); font-weight: 800; }
.mk.no { color: var(--muted); }
.tag { display: inline-block; font: 600 10px/1 var(--mono); letter-spacing: 0.12em; text-transform: uppercase; border: 1px solid var(--strong); padding: 4px 6px; margin-right: 8px; vertical-align: 2px; }
.oname { white-space: nowrap; }
.legend { font: 400 12px/1.5 var(--mono); color: var(--muted); }
h2 { font-size: 13px; font: 500 12px/1 var(--mono); letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); margin: 64px 0 8px; }
.opts { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 0 32px; border-top: 1px solid var(--line); }
.opt { padding: 24px 0; border-bottom: 1px solid var(--line); }
.opt h3 { margin: 0 0 8px; font-size: 20px; letter-spacing: -0.01em; }
.opt p { margin: 0 0 10px; color: var(--muted); }
.opt .err { color: var(--fg); font-weight: 600; }
.meta { font-size: 13px; }
code { font-family: var(--mono); font-size: 0.86em; }
.files { list-style: none; padding: 0; margin: 0; font-size: 13px; color: var(--muted); }
.appx { position: relative; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); }
.appx pre { margin: 0; padding: 24px 0; overflow-x: auto; font: 13px/1.6 var(--mono); color: var(--muted); white-space: pre; }
button { font: 600 14px/1 var(--sans); background: var(--fg); color: var(--bg); border: 0; padding: 12px 18px; cursor: pointer; margin-top: 16px; }
button:focus-visible { outline: 2px solid var(--fg); outline-offset: 3px; }
footer { padding: 56px 0 40px; font-size: 13px; color: var(--muted); display: flex; justify-content: space-between; gap: 16px; flex-wrap: wrap; }
@media (max-width: 720px) {
  .verdict { grid-template-columns: 1fr; gap: 8px; }
  .hero { padding: 48px 0 28px; }
}
</style>
</head>
<body>
<div class="wrap">
  <header class="bar">
    <span class="brand">Settle</span>
    <span class="muted">${esc(data.created_at.slice(0, 16).replace("T", " "))} UTC · base <code>${esc(data.base_commit.slice(0, 7))}</code></span>
  </header>

  <section class="hero">
    <div class="eyebrow">The question</div>
    <h1>${esc(data.question)}</h1>
    <p class="sub">${built} of ${data.options.length} options built by IBM Bob in parallel, each in its own branch, then measured with the same ${data.load.duration_seconds} second load test at concurrency ${data.load.concurrency}.</p>
  </section>

  <section class="verdict">
    <div class="k">Verdict</div>
    <div>
      <p class="h">${esc(data.verdict.headline)}</p>
      <p>${esc(data.verdict.reason)}</p>
    </div>
  </section>

  <div class="tablewrap">
    <table>
      <thead><tr><th scope="col"><span class="muted">Measured</span></th>${thead}</tr></thead>
      <tbody>
${tbody}
      </tbody>
    </table>
  </div>
  <p class="legend">✓ meets the constraint · ✕ misses it · first column is today's code, for reference</p>

  <h2>The options</h2>
  <div class="opts">
${details}
  </div>

  <h2>Design doc appendix</h2>
  <div class="appx"><pre id="appendix">${esc(appendix)}</pre></div>
  <button id="copy" type="button">Copy appendix</button>

  <footer>
    <span>Settle · options built with IBM Bob</span>
    <span>Numbers from this machine, this data, this run.</span>
  </footer>
</div>
<script>
document.getElementById("copy").addEventListener("click", async (e) => {
  const text = document.getElementById("appendix").textContent;
  try { await navigator.clipboard.writeText(text); e.target.textContent = "Copied"; }
  catch { e.target.textContent = "Select the text above to copy"; }
  setTimeout(() => (e.target.textContent = "Copy appendix"), 1800);
});
</script>
</body>
</html>
`;
}
