// HTML and Markdown builders for a run. Pure string functions with no Node
// imports, so the same code renders the page at build time and re-renders it
// in the browser when a reader changes a constraint.
import type { RunFile } from "./engine.ts";
import type { Check, OptionResult } from "./verdict.ts";

export const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);

const dash = "—";
const ms = (n?: number) => (n === undefined ? dash : n >= 1000 ? `${(n / 1000).toFixed(2)} s` : `${Math.round(n)} ms`);
const secs = (r: OptionResult) => {
  const f = r.freshness;
  if (!f) return dash;
  if (f.timed_out) return `over ${f.max_seconds} s`;
  return f.max_seconds < 1 ? "instant" : `${f.max_seconds} s`;
};
const lines = (r: OptionResult) => (r.diff ? `+${r.diff.added} −${r.diff.removed}` : dash);

interface Row {
  label: string;
  note?: string;
  value: (r: OptionResult) => string;
  check?: string;
}

function rows(data: RunFile): Row[] {
  const c = data.constraints;
  return [
    { label: "p95 latency", note: c.max_p95_ms !== undefined ? `needs ≤ ${c.max_p95_ms} ms` : undefined, value: (r) => ms(r.load?.p95_ms), check: "p95 latency" },
    { label: "Median latency", value: (r) => ms(r.load?.p50_ms) },
    { label: "Throughput", value: (r) => (r.load ? `${r.load.rps} req/s` : dash) },
    {
      label: "Staleness",
      note: c.max_staleness_seconds !== undefined ? `needs ≤ ${c.max_staleness_seconds} s` : "time until a new write shows up",
      value: secs,
      check: "Staleness",
    },
    { label: "Code changed", note: "application code, tests excluded", value: lines },
    { label: "Tests added", value: (r) => (r.diff?.test_added !== undefined ? `+${r.diff.test_added} lines` : dash) },
    { label: "Files touched", value: (r) => (r.diff ? String(r.diff.files.length) : dash) },
    {
      label: "New dependencies",
      note: c.max_new_dependencies !== undefined ? `needs ≤ ${c.max_new_dependencies}` : undefined,
      value: (r) => (r.new_dependencies ? (r.new_dependencies.length ? r.new_dependencies.join(", ") : "none") : dash),
      check: "New dependencies",
    },
    {
      label: "Tests",
      value: (r) => (r.tests ? (r.tests.timed_out ? "hung, never exited" : `${r.tests.ok ? "pass" : "fail"}${r.tests.passed !== null ? ` · ${r.tests.passed}` : ""}`) : dash),
      check: "Tests",
    },
    { label: "Built by Bob in", value: (r) => (r.bob ? `${Math.floor(r.bob.duration_seconds / 60)}m ${r.bob.duration_seconds % 60}s` : dash) },
  ];
}

function mark(checks: Check[] | undefined, label?: string): string {
  if (!checks || !label) return "";
  const c = checks.find((x) => x.label === label);
  if (!c) return "";
  return c.pass ? `<span class="mk ok" title="meets constraint">✓</span>` : `<span class="mk no" title="misses constraint">✕</span>`;
}

export function renderAppendix(data: RunFile): string {
  const all = [data.baseline, ...data.options];
  const table = rows(data);
  const head = `| | ${all.map((r) => r.name).join(" | ")} |\n|---|${all.map(() => "---").join("|")}|`;
  const body = table.map((row) => `| ${row.label} | ${all.map((r) => row.value(r)).join(" | ")} |`).join("\n");
  const constraints = Object.entries(data.constraints)
    .map(([k, v]) => `\`${k}: ${v}\``)
    .join(", ");
  const branches = data.options.map((o) => `- ${o.name}: \`${o.branch}\`${o.build_error ? ` (not built: ${o.build_error})` : ""}`).join("\n");
  return `## Appendix: measured comparison

**Question:** ${data.question}

Each option was built by IBM Bob in its own branch from \`${data.base_commit.slice(0, 7)}\`, then measured with the same load test (${data.load.duration_seconds} s at concurrency ${data.load.concurrency}) and the same staleness probe.

${head}
${body}

**Constraints:** ${constraints || "none"}

**Verdict:** ${data.verdict.headline} ${data.verdict.reason}

**Branches:**
${branches}

_Generated by Settle on ${data.created_at.slice(0, 10)}._
`;
}

export function renderVerdict(data: RunFile): string {
  return `<div class="k">Verdict</div>
<div>
  <p class="h">${esc(data.verdict.headline)}</p>
  <p>${esc(data.verdict.reason)}</p>
</div>`;
}

export function renderTable(data: RunFile): string {
  const all = [data.baseline, ...data.options];
  const winner = data.verdict.winner;
  const cls = (r: OptionResult) => (r.id === winner ? "win" : r.id === "baseline" ? "base" : "");
  const thead = all
    .map((r) => `<th class="${cls(r)}" scope="col">${r.id === winner ? `<span class="tag">Pick</span>` : ""}<span class="oname">${esc(r.name)}</span></th>`)
    .join("");
  const tbody = rows(data)
    .map(
      (row) => `<tr>
  <th scope="row"><span class="rl">${esc(row.label)}</span>${row.note ? `<span class="rn">${esc(row.note)}</span>` : ""}</th>
  ${all
    .map((r) => {
      const v = r.built ? row.value(r) : "not built";
      return `<td class="${cls(r)}">${esc(v)}${r.id === "baseline" ? "" : mark(data.verdict.checks[r.id], row.check)}</td>`;
    })
    .join("")}
</tr>`,
    )
    .join("\n");
  return `<table>
  <thead><tr><th scope="col"><span class="muted">Measured</span></th>${thead}</tr></thead>
  <tbody>
${tbody}
  </tbody>
</table>`;
}

export function renderOptions(data: RunFile): string {
  const winner = data.verdict.winner;
  return data.options
    .map(
      (o) => `<section class="opt">
  <h3>${esc(o.name)}${o.id === winner ? ` <span class="tag">Pick</span>` : ""}</h3>
  <p>${esc(o.description)}</p>
  ${o.build_error ? `<p class="err">Not built: ${esc(o.build_error)}</p>` : ""}
  ${o.measure_error ? `<p class="err">Measurement failed: ${esc(o.measure_error.split("\n")[0])}</p>` : ""}
  <p class="meta">Branch <code>${esc(o.branch)}</code></p>
  ${o.diff?.files.length ? `<ul class="files">${o.diff.files.map((f) => `<li><code>${esc(f)}</code></li>`).join("")}</ul>` : ""}
  ${o.diff?.test_files?.length ? `<ul class="files">${o.diff.test_files.map((f) => `<li><code>${esc(f)}</code> <span class="muted">test</span></li>`).join("")}</ul>` : ""}
</section>`,
    )
    .join("\n");
}

// Stepped values for the constraint sliders. The recorded constraint is
// inserted if it is not already a step, so the page opens on the real value.
export const STEPS = {
  max_p95_ms: [10, 25, 50, 100, 250, 500, 1000, 2000],
  max_staleness_seconds: [0, 1, 5, 10, 15, 30, 60, 90, 120],
} as const;

export type SliderKey = keyof typeof STEPS;

export function stepsFor(key: SliderKey, current: number | undefined): number[] {
  const steps: number[] = [...STEPS[key]];
  if (current !== undefined && !steps.includes(current)) steps.push(current);
  return steps.sort((a, b) => a - b);
}

export function renderControls(data: RunFile): string {
  const c = data.constraints;
  const slider = (key: SliderKey, label: string, unit: string) => {
    const value = c[key];
    if (value === undefined) return "";
    const steps = stepsFor(key, value);
    return `<label class="ctl">
  <span class="cl">${esc(label)}</span>
  <input type="range" min="0" max="${steps.length - 1}" step="1" value="${steps.indexOf(value)}" data-key="${key}" data-steps="${steps.join(",")}" aria-label="${esc(label)}">
  <output data-for="${key}">≤ ${value} ${unit}</output>
</label>`;
  };
  return [slider("max_p95_ms", "p95 latency", "ms"), slider("max_staleness_seconds", "Staleness", "s")].join("\n");
}
